### ISSUE TITLE
Deploying job system (replacing Celery and RabbitMQ)

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2097]
Collecting issues here for fixing 

- [x] cancel sim https://github.com/radiasoft/sirepo/issues/2144
- [x] dev start https://github.com/radiasoft/sirepo/issues/2079
- [x] fixup all examples https://github.com/radiasoft/sirepo/issues/2140
- [x] sbatch testing https://github.com/radiasoft/sirepo/pull/2139
- [x] better logging https://github.com/radiasoft/sirepo/issues/2135
- [x] cancel retry runner https://github.com/radiasoft/sirepo/issues/2128
- [x] flux jobRunMode https://github.com/radiasoft/sirepo/issues/2122
- [x] build test error https://github.com/radiasoft/sirepo/issues/2111
- [x] srunit exception https://github.com/radiasoft/sirepo/issues/2109
- [x] cancel frame error https://github.com/radiasoft/sirepo/issues/2107
- [x] error redirect https://github.com/radiasoft/sirepo/issues/2108
- [x] supervisor in all tests https://github.com/radiasoft/sirepo/issues/2061
- [x] Merge sbatch https://github.com/radiasoft/sirepo/pull/2096
- [x] Merge sbatch-auth https://github.com/radiasoft/sirepo/tree/sbatch-auth
- [x] Job timeouts https://github.com/radiasoft/sirepo/issues/1435
- [x] Docker resources https://github.com/radiasoft/sirepo/issues/2102
- [x] serverUpgrade needs to reload https://github.com/radiasoft/sirepo/issues/2071
- [x] rsconf https://github.com/radiasoft/rsconf/issues/101
- [x] cores & hours https://github.com/radiasoft/sirepo/issues/2098
- [x] modal auth https://github.com/radiasoft/sirepo/issues/2099
- [x] libFilesUri https://github.com/radiasoft/sirepo/issues/2100
- [x] supervisor read run dir https://github.com/radiasoft/sirepo/issues/2101
- [x] reverse of undefined https://github.com/radiasoft/sirepo/issues/2126
- [x] email login on firefox causes error log https://github.com/radiasoft/sirepo/issues/2130
- [x] SRW import python failure https://github.com/radiasoft/sirepo/issues/2131
- [x] fixup on other entry points https://github.com/radiasoft/sirepo/issues/2133

After alpha:
- [ ] docker timeout https://github.com/radiasoft/sirepo/issues/2105
- [ ] remove lib files https://github.com/radiasoft/sirepo/issues/2078

After beta:
- [ ] curl installer https://github.com/radiasoft/download/issues/75

**Comment by robnagler** [comment]
Moved open issues to #2148. Ready to deploy.
