### ISSUE TITLE
Outstanding job system work

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2148]
Issues with * are important for prod release:

- [x] * authState should be dynamic so we don't need redirects #2227
- [x] * Consider how to implement job_cmd as fixed process #2226
- [x] * Test performance of get_simulation_frame vs get_data_file #2225
- [ ] Should websocket_free toss exception? #2224
- [x] * cookieRedirect is broken #2223
- [x] Sbatch: Error PKDict has no attribute 'shifterImage' #2216
- [x] simulationFrame requested right before runSimulation #2211
- [ ] test.sh needs to run sbatch, docker, local in dev (not build) #2210
- [x] Conflict. The container name "snip" is already in use by container #2206
- [ ] asynchronous test driver #2204
- [ ] run codes in subprocess #2201
- [ ] * Report not generated on top of simulation screen #2199
- [x] * sbatch: invalid enum "JobRunMode" value for field "jobRunMode" #2198
- [ ] job-supervisor db files can be pretty big #2196
- [x] job_agent.pid_file should not be removed if not "this" agent #2195
- [x] Sbatch: Error getting raw data file #2181
- [ ] sbatch needs to interrogate queue #2178
- [ ] sbatch run_dirs can be mucked with #2176
- [ ] sbatch creds can't change #2175
- [ ] sbatchLogin needs to be more secure #2174
- [x] Agent start timeout #2171
- [ ] NERSC: agents should log hostname #2167
- [x] Sbatch: GUI remembers the username and password? #2166
- [ ] update GUI on NERSC shifter failure #2165
- [x] run parallel simulation not working on alpha #2164
- [x] docker unable to open in-json #2163
- [x] agent restarts on websocket failure #2162
- [x] redirect loop for server upgrade #2160
- [x] ignore src user in upgrade #2159
- [ ] Remove invalid run dirs #2158
- [x] nersc release program #2154
- [x] mpi cores #2153
- [x] Need driver dependent supervisor_uri #2152
- [x] Lag between canceling a sim and all frames coming back #2149
- [x] improve job supervisor/agent logging #2135
- [x] downloadDataFile fails with not found (404) when cancel #2127
- [x] Docker agent idle timeout #2105
- [x] job_supervisor tries to find run dir if not db #2101
- [x] Job execution speed #2091
- [ ] using nginx proxy for remote agent files #2081
- [x] look at agent startup time #2080
- [ ] remove lib files #2078
- [x] start job_supervisor in service.http #2079
- [ ] get_data_file reaches back to simulation_db #2065
- [ ] When a simulation is stopped for a resource constraint, notify the user #2057
- [x] when compute_job != report, minimizing one report, cancels all #1999
- [ ] reaching inside other run directories #1950
- [ ] serial selected, job run in serial queue #1874
- [ ] Elegant bunchCompLSC - lattice time not updating #1865
- [ ] elegant: sometimes the simulation progress bar behaves badly #1836
- [x] runner_test should assert sirepo versions #1556
- [x] Automate multi-host Docker execution #1442
- [x] Stop job after timeout #1435
- [ ] Process disk use and run-time monitor #1312
- [ ] Need structure to server API requests and responses #422
- [ ] deleteSimulation should cancel jobs #400
- [ ] Server should clear run directories if out of sync with models #343
- [x] Run simulation in a particular version container #327
- [x] version not saved in simulation run directory #266
- [x] Need to query running simulations #60
- [x] curl installer radiasoft/download #75
- [x] Remove runner #2516

**Comment by robnagler** [comment]
Switching to milestones to group issues.
