### ISSUE TITLE
Script example failure

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6602]
The elegant "Script Element Example" is failing with the error:
```
sh: line 1: ./SCRIPT-commandFile.combine.py: cannot execute: required file not found
```

This error does not appear on dev.

Additionally, the script element may be required for an upcoming project, so these script-related issues should also be addressed:

- [x]  #3915 occasional memory error with script element (I believe this is fixed with the elegant version we are using)

- [x] #5813 edit script element error

- [x] #5812 custom script name error

**Comment by moellep** [comment]
The script example was failing for me because I was still using a local copy of the combine.py. Removing the file, and the example works correctly. I'll keep this issue open to track the 3 other script related issues as a group.

**Comment by moellep** [comment]
These issues are fixed with #6605
